import Americo from '../assets/img/Americo.png';
import AMAM from '../assets/img/AMAM.jpeg'
import AETNA from '../assets/img/AETNA.png'
import CFLIC from '../assets/img/CFLIC.png'
import CFG from '../assets/img/CFG.png'
import Foresters from '../assets/img/Foresters.jpeg'
import Gerber from '../assets/img/Gerber.jpeg'
import GW from '../assets/img/GW.png'
import GTL from '../assets/img/GTL.png'
import LBL from '../assets/img/LBL.png'
import Lifeshield from '../assets/img/Lifeshield.png'
import MOO from '../assets/img/MOO.png'
import Oxford from '../assets/img/Oxford.png'
import Prosperity from '../assets/img/Prosperity.jpeg'
import RNA from '../assets/img/RNA.jpeg'
import TransAmerica from '../assets/img/TransAmerica.png'
import Trinity from '../assets/img/Trinity.png'

export const FE_COMPANIES = [
    {
        id: 0,
        name: 'AETNA',
        image: AETNA,
        address: '1021 Reams Fleming Boulevard',
        city: 'Franklin',
        state: 'TN',
        zipcode: '37064',
        phone: '866-272-6630',
        fax: '',
    },
    {
        id: 1,
        name: 'American Amicable',
        image: AMAM,
        address: 'PO Box 2549',
        city: 'Waco',
        state: 'TX',
        zipcode: '76702',
        phone: '800-736-7311',
        fax: '254-297-2105',
    },
    {
        id: 2,
        name: 'Americo',
        image: Americo,
        address: 'PO Box 410288',
        city: 'Kansas City',
        state: 'MO',
        zipcode: '64141',
        phone: '800-231-0801',
        fax: '800-395-9238',
    },
    {
        id: 3,
        name: 'Christian Fidelity',
        image: CFLIC,
        address: '2721 North Central Avenue',
        city: 'Phoenix',
        state: 'AZ',
        zipcode: '85004',
        phone: '888-863-6674',
        fax: '833-316-0357',
    },
    {
        id: 4,
        name: 'Columbian Financial Group',
        image: CFG,
        address: '',
        city: 'Binghamton',
        state: 'NY',
        zipcode: '',
        phone: '800-423-9765',
        fax: '',
    },
    {
        id: 5,
        name: 'Foresters',
        image: Foresters,
        address: 'PO Box 179',
        city: 'Buffalo',
        state: 'NY',
        zipcode: '14201',
        phone: '800-828-1540',
        fax: '',
    },
    {
        id: 6,
        name: 'Gerber',
        image: Gerber,
        address: '445 State Street',
        city: 'Fremont',
        state: 'MI',
        zipcode: '49412',
        phone: '800-704-2180',
        fax: '231-928-3078',
    },
    {
        id: 7,
        name: 'Great Western',
        image: GW,
        address: 'PO Box 14410',
        city: 'Des Moines',
        state: 'IA',
        zipcode: '50306',
        phone: '800-733-5454',
        fax: '801-689-1394',
    },
    {
        id: 8,
        name: 'Guaranteed Trust Life',
        image: GTL,
        address: '1275 Milwaukee Avenue',
        city: 'Glenview',
        state: 'IL',
        zipcode: '60025',
        phone: '800-323-6907',
        fax: '847-298-1215',
    },
    {
        id: 9,
        name: 'Liberty Bankers',
        image: LBL,
        address: 'PO Box 224',
        city: 'Brownwood',
        state: 'TX',
        zipcode: '76804',
        phone: '800-972-6615',
        fax: '866-505-9377',
    },
    {
        id: 10,
        name: 'Lifeshield',
        image: Lifeshield,
        address: '5500 North Western Ave, Suite 200',
        city: 'Oklahoma City',
        state: 'OK',
        zipcode: '73118',
        phone: '800-851-5041',
        fax: '',
    },
    {
        id: 11,
        name: 'Mutual of Omaha',
        image: MOO,
        address: '3300 Mutual of Omaha Plaza',
        city: 'Omaha',
        state: 'NE',
        zipcode: '68175',
        phone: '800-775-6000',
        fax: '',
    },
    {
        id: 12,
        name: 'Oxford',
        image: Oxford,
        address: '2721 N Central Ave',
        city: 'Phoenix',
        state: 'AZ',
        zipcode: '85004',
        phone: '866-641-9999',
        fax: '877-584-2777',
    },
    {
        id: 13,
        name: 'Prosperity',
        image: Prosperity,
        address: '100 West 33rd Street Suite 1007',
        city: 'New York',
        state: 'NY',
        zipcode: '10001',
        phone: '877-725-4872',
        fax: '',
    },
    {
        id: 14,
        name: 'Royal Neighbors of America',
        image: RNA,
        address: '230 16th Street',
        city: 'Rock Island',
        state: 'IL',
        zipcode: '61201',
        phone: '800-627-4762',
        fax: '',
    },
    {
        id: 15,
        name: 'TransAmerica',
        image: TransAmerica,
        address: 'PO Box 189',
        city: 'Cedar Rapids',
        state: 'IA',
        zipcode: '52406',
        phone: '800-797-2643',
        fax: '972-881-4527',
    },
    {
        id: 16,
        name: 'Trinity',
        image: Trinity,
        address: '7633 East 63rd Place Suite 230',
        city: 'Tulsa',
        state: 'OK',
        zipcode: '74133',
        phone: '918-249-2438',
        fax: '',
    },
]